### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by skaldebane** [andrewbailey/Difference#3]
Hi! This library is super useful for me in one of my projects, but I'm not sure if there are any stability guarantees for this?
Is this library pretty much stable for usage or are there any gotchas?

**Comment by andrewbailey** [comment]
Hey! You're right that not much has happened since the 1.0 release. I consider that to be API stable, and I'm not aware of any issues in the algorithm's implementation. And although it was compiled for Kotlin 1.3.72, you should be able to continue using it with newer versions of Kotlin since the language hasn't made changes that break old binaries (at least on the JVM — there might be some issues depending on Difference with newer versions of Kotlin/Native or Kotlin/JS, but I'm unaware of anything at the moment).

Despite Difference not being actively worked on, I consider it to be stable. I don't have any plans to add more features at this time, but I would support as necessary. And my guess is that this commitment mostly involves managing builds. The library itself is very lean, using only Kotlin built-ins and having no third-party dependencies (It doesn't even use coroutines internally — the standard library is the only library that Difference depends on when you pull it into your project).

All that said, you should be able to expect Difference to remain functional and continue working with minimal support. An unexpectedly major Kotlin update could throw a wrench into those plans, but I would almost certainly want to keep it alive as I've used the library as a dependency both in a personal and professional project.

Hopefully that adds more context here and helps you make a decision! And if there is something that I've missed maintenance-wise that's preventing Difference from working for you, please file another issue!

**Comment by skaldebane** [comment]
Thanks a lot for your response! I'll give it a shot and tell you if I face any issues.
Thanks for making this library!
